package Lab9p2;

/**
 *
 * @author ELIZABETH HERNANDEZ
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        jp_clerigo.setVisible(false);
        jp_mago.setVisible(false);
        jp_barbaro.setVisible(false);
        jp_picaro.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jc_clase = new javax.swing.JComboBox<>();
        jp_clerigo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jt_dd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt_inv = new javax.swing.JTextField();
        jp_mago = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jp_barbaro = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jc_arma = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jp_picaro = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jc_inst = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jt_robos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jc_Raza = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jt_descripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_estatura = new javax.swing.JTextField();
        jLabel6peso = new javax.swing.JLabel();
        jt_Peso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jt_edad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jc_nac = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jb_crear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccione la clase de personaje");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jc_clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clerigo", "Barbaro", "Mago", "Picaro" }));
        jc_clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_claseActionPerformed(evt);
            }
        });
        jPanel1.add(jc_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 171, -1));

        jLabel3.setText("Dios o demonio en el que cree");

        jLabel6.setText("Tipo de invocacion");

        javax.swing.GroupLayout jp_clerigoLayout = new javax.swing.GroupLayout(jp_clerigo);
        jp_clerigo.setLayout(jp_clerigoLayout);
        jp_clerigoLayout.setHorizontalGroup(
            jp_clerigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_clerigoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_clerigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jt_dd, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jt_inv))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jp_clerigoLayout.setVerticalGroup(
            jp_clerigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_clerigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jt_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jt_inv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.add(jp_clerigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 71, 350, 170));

        jLabel10.setText("Tipo de Magia");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mago Blanco", "Mago negro", "Mago Sanador" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_magoLayout = new javax.swing.GroupLayout(jp_mago);
        jp_mago.setLayout(jp_magoLayout);
        jp_magoLayout.setHorizontalGroup(
            jp_magoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_magoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_magoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jp_magoLayout.setVerticalGroup(
            jp_magoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_magoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jPanel1.add(jp_mago, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 71, 350, 210));

        jLabel11.setText("Tipo de arma");

        jc_arma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesada", "Ligera", "Escudo" }));

        jLabel12.setText("Nivel de XP");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jp_barbaroLayout = new javax.swing.GroupLayout(jp_barbaro);
        jp_barbaro.setLayout(jp_barbaroLayout);
        jp_barbaroLayout.setHorizontalGroup(
            jp_barbaroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_barbaroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_barbaroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jc_arma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jp_barbaroLayout.setVerticalGroup(
            jp_barbaroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_barbaroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jc_arma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel1.add(jp_barbaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 68, 350, 210));

        jLabel13.setText("Tipo de instrumento ");

        jc_inst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amuleto", "Arma", "Piedra Antigua" }));

        jLabel14.setText("Cantidad de robos exitosos realizados");

        javax.swing.GroupLayout jp_picaroLayout = new javax.swing.GroupLayout(jp_picaro);
        jp_picaro.setLayout(jp_picaroLayout);
        jp_picaroLayout.setHorizontalGroup(
            jp_picaroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_picaroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_picaroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_inst, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jt_robos))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jp_picaroLayout.setVerticalGroup(
            jp_picaroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_picaroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jc_inst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jt_robos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel1.add(jp_picaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 71, 360, 210));

        jLabel2.setText("Descripcion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 180, -1));
        jPanel1.add(jt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 160, -1));

        jc_Raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mediano", "Enano", "Elfo", "Humano" }));
        jPanel1.add(jc_Raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, -1));

        jLabel4.setText("Seleccione la raza de su personaje:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, -1));
        jPanel1.add(jt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, -1));

        jLabel5.setText("Estatura:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 180, -1));
        jPanel1.add(jt_estatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, -1));

        jLabel6peso.setText("Peso:");
        jPanel1.add(jLabel6peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, -1));
        jPanel1.add(jt_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, -1));

        jLabel7.setText("Edad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 180, -1));
        jPanel1.add(jt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 160, -1));

        jLabel8.setText("Nombre:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 60, -1));

        jc_nac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Norfair", "Brinstar", "Maridia", "Zebes", "Crateria" }));
        jPanel1.add(jc_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 150, -1));

        jLabel9.setText("Nacionalidad:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 80, -1));

        jb_crear.setText("Crear");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });
        jPanel1.add(jb_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jTabbedPane1.addTab("Crear Personajes", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar Personajes", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver atributos de un personaje", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar personajes", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Combate", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jc_claseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_claseActionPerformed
        // TODO add your handling code here:
        String clase = jc_clase.getSelectedItem().toString();
        if (clase.equals("Clerigo")) {
            jp_clerigo.setVisible(true);
            
        jp_mago.setVisible(false);
        jp_barbaro.setVisible(false);
        jp_picaro.setVisible(false);
            
        }
        if (clase.equals("Barbaro")) {
            jp_barbaro.setVisible(true);
            jp_clerigo.setVisible(false);
        jp_mago.setVisible(false);
       
        jp_picaro.setVisible(false);
        }
        
        if (clase.equals("Mago")) {
            jp_mago.setVisible(true);
            jp_clerigo.setVisible(false);
        
        jp_barbaro.setVisible(false);
        jp_picaro.setVisible(false);
        }
        if (clase.equals("Picaro")) {
            jp_picaro.setVisible(true);
            jp_clerigo.setVisible(false);
        jp_mago.setVisible(false);
        jp_barbaro.setVisible(false);
        
        }
    }//GEN-LAST:event_jc_claseActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked
        // TODO add your handling code here:
        String clase = jc_clase.getSelectedItem().toString();
        
        
        
    }//GEN-LAST:event_jb_crearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6peso;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_crear;
    private javax.swing.JComboBox<String> jc_Raza;
    private javax.swing.JComboBox<String> jc_arma;
    private javax.swing.JComboBox<String> jc_clase;
    private javax.swing.JComboBox<String> jc_inst;
    private javax.swing.JComboBox<String> jc_nac;
    private javax.swing.JPanel jp_barbaro;
    private javax.swing.JPanel jp_clerigo;
    private javax.swing.JPanel jp_mago;
    private javax.swing.JPanel jp_picaro;
    private javax.swing.JTextField jt_Peso;
    private javax.swing.JTextField jt_dd;
    private javax.swing.JTextField jt_descripcion;
    private javax.swing.JTextField jt_edad;
    private javax.swing.JTextField jt_estatura;
    private javax.swing.JTextField jt_inv;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_robos;
    // End of variables declaration//GEN-END:variables
}
